AllCops:
  Include:
    - 'lib/**/*.rb'
    - 'ext/**/*.rb'
  Exclude:
    - '**/*.spec'
    - '**/*.erb'
    - 'acceptance/**/*'
    - 'autotest/**/*'
    - 'spec/**/*'
    - 'tasks/**/*'
    - 'lib/puppet/vendor/**/*'
    - 'lib/puppet/parser/parser.rb'
    - 'lib/puppet/pops/parser/eparser.rb'
    - 'lib/puppet/external/nagios/parser.rb'
    - 'lib/puppet/module_tool/skeleton/**/*'
    - 'lib/semantic_puppet/dependency/module_release.rb'

  DisabledByDefault: true

Security/YAMLLoad:
  Enabled: true

#Security/Eval:
#  Enabled: true

