language: ruby
sudo: false
bundler_args: --without development
script:
  - "ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'"
  - "ls -l spec/fixtures/unit/ssl/certificate"
  - "ls -l spec/fixtures/unit/ssl/certificate_request"
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.2.0
  - 2.1.5
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"

matrix:
  exclude:
    - rvm: 2.2.0
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
