language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  - gem update --system && gem install bundler --no-document
  - ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION; puts OpenSSL::OPENSSL_LIBRARY_VERSION'
script:
  - "bundle exec rspec spec/integration/http/client_spec.rb"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.3
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.4
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.5
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.6
      env: "CHECK=parallel:spec\\[2\\]"
