language: ruby
sudo: false
bundler_args: --without development extra
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.5.1
  - 2.4.0
  - 2.3.6

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"
  - "CHECK=warnings"

matrix:
  exclude:
    - rvm: 2.3.6
      env: "CHECK=rubocop"
    - rvm: 2.3.6
      env: "CHECK=commits"
    - rvm: 2.3.6
      env: "CHECK=warnings"
