language: ruby
bundler_args: --without development
script: "bundle exec rake spec"
notifications:
  email: false
rvm:
  - 2.1.0
  - 1.9.3
  - 1.8.7
  - ruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
