language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  gem update --system --force
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.3
      env: "CHECK=parallel:spec\\[1\\] TESTS=spec/integration/application/agent_spec.rb"

    - rvm: 2.4
      env: "CHECK=parallel:spec\\[1\\] TESTS=spec/integration/application/agent_spec.rb"

    - rvm: 2.5
      env: "CHECK=parallel:spec\\[1\\] TESTS=spec/integration/application/agent_spec.rb"

    - rvm: 2.6
      env: "CHECK=parallel:spec\\[1\\] TESTS=spec/integration/application/agent_spec.rb"
