language: ruby
sudo: false
bundler_args: --jobs 4 --retry 2 --without packaging documentation
before_install:
  gem update --system --force
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false

matrix:
  include:
    - rvm: 2.5
      env: "CHECK=parallel:spec\\[2\\]"

    - rvm: 2.5
      env: "CHECK=rubocop"

    - rvm: 2.5
      env: "CHECK=commits"

    - rvm: 2.5
      env: "CHECK=warnings"
