language: ruby
sudo: false
bundler_args: --without development extra
script:
  - "bundle exec rake $CHECK"
notifications:
  email: false
rvm:
  - 2.4.0
  - 2.3.6
  - 2.2.9
  - 2.1.9
  - 2.0.0
  - 1.9.3

env:
  - "CHECK=parallel:spec\\[2\\]"
  - "CHECK=rubocop"
  - "CHECK=commits"
  - "CHECK=warnings"

matrix:
  exclude:
    - rvm: 2.4.0
      env: "CHECK=rubocop"
    - rvm: 2.3.6
      env: "CHECK=rubocop"
    - rvm: 2.2.9
      env: "CHECK=rubocop"
    - rvm: 2.0.0
      env: "CHECK=rubocop"
    - rvm: 1.9.3
      env: "CHECK=rubocop"
    - rvm: 2.4.0
      env: "CHECK=commits"
    - rvm: 2.3.6
      env: "CHECK=commits"
    - rvm: 2.2.9
      env: "CHECK=commits"
    - rvm: 2.0.0
      env: "CHECK=commits"
    - rvm: 1.9.3
      env: "CHECK=commits"
    - rvm: 2.3.6
      env: "CHECK=warnings"
    - rvm: 2.2.9
      env: "CHECK=warnings"
    - rvm: 2.1.9
      env: "CHECK=warnings"
    - rvm: 2.0.0
      env: "CHECK=warnings"
    - rvm: 1.9.3
      env: "CHECK=warnings"
