version: 4.1.0.{build}
clone_depth: 10
install:
build: off
matrix:
  fast_finish: false

# Ruby versions under test
platform:
  - Ruby26-x64
  - Ruby25-x64
  - Ruby24-x64
  - Ruby23-x64

test_script:
  # The sleep is needed to allow the Appveyor tracing to start correctly after a reboot (locale change)
  # - ps: Start-Sleep -Seconds 5
  - timeout 6
  - ps: |
      chcp
      Get-WinSystemLocale
      $Env:PATH = "C:\${Env:PLATFORM}\bin;${Env:PATH}"
      $Env:LOG_SPEC_ORDER = 'true'
      Get-ChildItem Env: | % { Write-Output "$($_.Key): $($_.Value)"  }
      # list current OpenSSL install
      gem list openssl
      ruby -ropenssl -e 'puts \"OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}\"; puts \"OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}\"'
      bundle install --jobs 4 --retry 2 --without packaging documentation
      Get-Content Gemfile.lock
      ruby -v
      gem --version
      bundle --version
      bundle exec rake parallel:spec[1] TESTS=spec/integration/application/agent_spec.rb
      $exitCode = $LASTEXITCODE
      Write-Output "Spec run exited with $exitCode"
      $host.SetShouldExit($exitCode)
on_failure:
  - appveyor PushArtifact .\spec_order.txt
notifications:
  - provider: Email
    to:
    - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
