version: 4.1.0.{build}
clone_depth: 10
install:
build: off

environment:
  matrix:
  - RUBY_VER: 23-x64
  - RUBY_VER: 22-x64
  - RUBY_VER: 21-x64

test_script:
  - SET
  - SET PATH=C:\Ruby%RUBY_VER%\bin;%PATH%
  - SET LOG_SPEC_ORDER=true
  - bundle install --jobs 4 --retry 2 --without development extra
  - type Gemfile.lock
  - ruby -v
  - bundle exec rspec spec

on_failure:
  - appveyor PushArtifact .\spec_order.txt
notifications:
  - provider: Email
    to:
    - nobody@nowhere.com
    on_build_success: false
    on_build_failure: false
    on_build_status_changed: false
