HOSTS:
  master:
    roles:
      - master
    platform: el-6-x86_64
    hypervisor: vcloud
    template: redhat-6-x86_64
    systembindir: /opt/puppetlabs/agent/bin
    puppetconfdir: /etc/puppetlabs/agent
    puppetcodedir: /etc/puppetlabs/agent
    puppetvardir: /opt/puppetlabs/agent/cache
    distmoduledir: /etc/puppetlabs/agent/modules
    # puppet-agent 0.3.1 package on the master still uses /usr/share
    sitemoduledir: /usr/share/puppet/modules
    hieraconf: /etc/puppetlabs/puppet/hiera.yaml
    puppetserver-confdir: /etc/puppetserver/conf.d/
  rhel-agent:
    roles:
      - agent
    platform: el-6-i386
    hypervisor: vcloud
    template: redhat-6-i386
  fedora-agent:
    roles:
      - agent
    platform: fedora-18-i386
    hypervisor: vcloud
    template: fedora-18-i386
  ubuntu-agent:
    roles:
      - agent
    platform: ubuntu-lucid-i386
    hypervisor: vcloud
    template: ubuntu-1004-i386
  wheezy-agent:
    roles:
      - agent
    platform: debian-wheezy-i386
    hypervisor: vcloud
    template: debian-7-i386
  centos-agent:
    roles:
      - agent
    platform: centos-5-i386
    hypervisor: vcloud
    template: centos-5-i386
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
