HOSTS:
  master:
    roles:
      - master
    platform: ubuntu-precise-x86_64
    hypervisor: vcloud
    template: ubuntu-1204-x86_64
    systembindir: /opt/puppetlabs/agent/bin
    puppetconfdir: /etc/puppetlabs/agent
    puppetcodedir: /etc/puppetlabs/agent
    puppetvardir: /opt/puppetlabs/agent/cache
    distmoduledir: /etc/puppetlabs/agent/modules
    # puppet-agent 0.3.1 package on the master still uses /usr/share
    sitemoduledir: /usr/share/puppet/modules
    hieraconf: /etc/puppetlabs/puppet/hiera.yaml
    puppetserver-confdir: /etc/puppetserver/conf.d/
  agent:
    roles:
      - agent
    platform: ubuntu-precise-i386
    hypervisor: vcloud
    template: ubuntu-1204-i386
CONFIG:
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
