---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vmpooler
    template: redhat-7-x86_64
  solaris-11-sparc:
    roles:
      - agent
    platform: solaris-11-sparc
    hypervisor: none
    ip: 10.32.114.245
    vmhostname: sol11-1.delivery.puppetlabs.net
CONFIG:
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
