HOSTS:
  master:
    roles:
      - master
      - agent
    platform: solaris-11-x86_64
    hypervisor: vcloud
    template: solaris-112-x86_64
  agent:
    roles:
      - agent
    platform: solaris-11-x86_64
    hypervisor: vcloud
    template: solaris-112-x86_64
CONFIG:
  filecount: 12
  datastore: instance0
  resourcepool: delivery/Quality Assurance/FOSS/Dynamic
  folder: Delivery/Quality Assurance/FOSS/Dynamic
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
