---
HOSTS:
  master:
    roles:
      - master
    platform: el-7-x86_64
    hypervisor: vmpooler
    template: redhat-7-x86_64
  solaris-10-sparc:
    roles:
      - agent
    platform: solaris-10-sparc
    hypervisor: none
    ip: 10.32.121.124
    vmhostname: sol10-1.delivery.puppetlabs.net
CONFIG:
  pooling_api: http://vmpooler.delivery.puppetlabs.net/
