---
name: RSpec tests

on:
  push:
    branches: [6.x]
  pull_request:
    branches: [6.x]

jobs:
  rspec_tests:
    name: ${{ matrix.cfg.os }}(ruby ${{ matrix.cfg.ruby }})
    strategy:
      matrix:
        cfg:
          - {os: ubuntu-18.04, ruby: 2.3}
          - {os: ubuntu-18.04, ruby: 2.4}
          - {os: ubuntu-18.04, ruby: 2.5}
          - {os: ubuntu-18.04, ruby: 2.6}
          - {os: ubuntu-18.04, ruby: 2.7}
          - {os: ubuntu-18.04, ruby: jruby-9.2.9.0}
          - {os: windows-2016, ruby: 2.4}
          - {os: windows-2016, ruby: 2.5}
          - {os: windows-2016, ruby: 2.6}

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.cfg.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle config set without packaging documentation
          bundle install --jobs 4 --retry 3

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        run: |
          # from: https://github.com/MSP-Greg/ruby/blob/4f1147e6555bbb7f0868bca40c86ca078a7381c3/.github/workflows/mingw.yml
          # Actions uses UTF8, causes test failures, similar to normal OS setup
          $PSDefaultParameterValues['*:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("IBM437")
          [Console]::InputEncoding  = [System.Text.Encoding]::GetEncoding("IBM437")
          $Env:LOG_SPEC_ORDER = 'true'

          # debug information
          chcp
          Get-WinSystemLocale
          Get-ChildItem Env: | % { Write-Output "$($_.Key): $($_.Value)"  }
          # list current OpenSSL install
          gem list openssl
          ruby -ropenssl -e 'puts \"OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}\"; puts \"OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}\"'
          Get-Content Gemfile.lock
          ruby -v
          gem --version
          bundle --version

          # Run tests
          bundle exec rake parallel:spec[2]

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: |
          # debug information
          gem list openssl
          ruby -ropenssl -e 'puts "OpenSSL Version - #{OpenSSL::OPENSSL_VERSION}"; puts "OpenSSL Library Version - #{OpenSSL::OPENSSL_LIBRARY_VERSION}"'
          cat Gemfile.lock
          ruby -v
          gem --version
          bundle --version

          if [[ ${{ matrix.cfg.ruby }} =~ "jruby" ]]; then
            export _JAVA_OPTIONS='-Xmx1024m -Xms512m'

            # workaround for PUP-10683
            sudo apt remove rpm
          fi

          bundle exec rake parallel:spec[2]
