---
name: RSpec tests

on:
  push:
    branches: [main]
    paths-ignore: ['**.md', 'docs/*', 'examples/*', 'ext/*', 'benchmarks/*']
  pull_request:
    paths-ignore: ['**.md', 'docs/*', 'examples/*', 'ext/*', 'benchmarks/*']

jobs:
  rspec_tests:
    name: ${{ matrix.cfg.os }}(ruby ${{ matrix.cfg.ruby }})
    strategy:
      matrix:
        cfg:
          - {os: ubuntu-18.04, ruby: 2.5}
          - {os: ubuntu-18.04, ruby: 2.6}
          - {os: ubuntu-18.04, ruby: 2.7}
          - {os: ubuntu-18.04, ruby: jruby-9.2.9.0}
          - {os: windows-2016, ruby: 2.5}
          - {os: windows-2016, ruby: 2.6}
          - {os: windows-2016, ruby: 2.7}

    runs-on: ${{ matrix.cfg.os }}
    steps:
      - name: Checkout current PR
        uses: actions/checkout@v2

      - name: Install ruby version ${{ matrix.cfg.ruby }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.cfg.ruby }}

      - name: Install bundler and gems
        run: |
          gem install bundler
          bundle config set without packaging documentation
          bundle install --jobs 4 --retry 3

      - name: Run tests on Windows
        if: runner.os == 'Windows'
        run: |
          # https://github.com/ruby/ruby/pull/2791/files#diff-ff5ff976e81bebd977f0834e60416abbR97-R100
          # Actions uses UTF8, causes test failures, similar to normal OS setup
          $PSDefaultParameterValues['*:Encoding'] = 'utf8'
          [Console]::OutputEncoding = [System.Text.Encoding]::GetEncoding("IBM437")
          [Console]::InputEncoding  = [System.Text.Encoding]::GetEncoding("IBM437")

          bundle exec rake parallel:spec[2]

      - name: Run tests on Linux
        if: runner.os == 'Linux'
        run: |
          if [[ ${{ matrix.cfg.ruby }} =~ "jruby" ]]; then
            export _JAVA_OPTIONS='-Xmx1024m -Xms512m'

            # workaround for PUP-10683
            sudo apt remove rpm
          fi
          bundle exec rake parallel:spec[2]
